# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdev < Formula
  desc "AI Coding Agent Server - Remote monitoring and control of AI coding agents from mobile devices"
  homepage "https://github.com/brianly1003/Cdev"
  version "0.1.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.3/cdev_0.1.3_darwin_amd64.tar.gz"
      sha256 "36c54d89dbf4d0bc1830cfb1b23e14931f615d2e69e71d830421803b6982cc5b"

      define_method(:install) do
        bin.install "cdev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.3/cdev_0.1.3_darwin_arm64.tar.gz"
      sha256 "6959684625b0ca522d51d527a649bd3efd666c7a5fde171b9190ba3140c269e2"

      define_method(:install) do
        bin.install "cdev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.3/cdev_0.1.3_linux_amd64.tar.gz"
      sha256 "3a04089f57158b8bc2bc179aa77f1d25589b0482314fd5ef29fb74e799152aee"
      define_method(:install) do
        bin.install "cdev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.3/cdev_0.1.3_linux_arm64.tar.gz"
      sha256 "70d6f943b352ec477f9015492afd51e3f99ed9cd1646a13e68d649398c636024"
      define_method(:install) do
        bin.install "cdev"
      end
    end
  end

  test do
    system "#{bin}/cdev", "version"
  end
end
