# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdev < Formula
  desc "AI Coding Agent Server - Remote monitoring and control of AI coding agents from mobile devices"
  homepage "https://github.com/brianly1003/Cdev"
  version "0.1.1"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.1/cdev_0.1.1_darwin_amd64.tar.gz"
      sha256 "512f7ec76e2a4bf3376f68bee5d3884b1bd7823ef673af062ec2727da0055cb3"

      def install
        bin.install "cdev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.1/cdev_0.1.1_darwin_arm64.tar.gz"
      sha256 "84c4663ab6268c41c25407cdf0ae5b022568fa58c4f624cefce626c1e3e503e4"

      def install
        bin.install "cdev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.1/cdev_0.1.1_linux_amd64.tar.gz"
      sha256 "3294e6d99e0ac2ce83ca322af9c5c13e5473dc3eee15868b1997de441eb353b7"
      def install
        bin.install "cdev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianly1003/cdev-releases/releases/download/v0.1.1/cdev_0.1.1_linux_arm64.tar.gz"
      sha256 "bdacc38e28b922a6164202b7e0775f10e5d7164625ca79fb142488f82908953a"
      def install
        bin.install "cdev"
      end
    end
  end

  test do
    system "#{bin}/cdev", "version"
  end
end
